language: python
python:
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - python setup.py develop


script:
  # Install and Run flake8
  - python setup.py flake8
  - python setup.py bdist_wheel
